### ISSUE TITLE
 IOS Simulator Crashes: Runner quit unexpectedly in Flutter build 

### ISSUE THREAD

**Issue by mdtaqi98** [getgauge/gauge-ruby#103]
POD File:
```
# platform :ios, '12.2'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do

    use_frameworks!
    pod 'Firebase/Core'

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }
  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

Process:               Runner [8244]
Path:                  /Users/USER/Library/Developer/CoreSimulator/Devices/649A0E13-9AA1-4F2B-9458-99DD1FC2CD19/data/Containers/Bundle/Application/F4B6622F-3DA2-423A-B85D-203880CD657E/Runner.app/Runner
Identifier:            Runner
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd_sim [5880]
Responsible:           Runner [8244]
User ID:               501

Date/Time:             2019-03-28 15:13:49.870 +0530
OS Version:            Mac OS X 10.14.3 (18D109)
Report Version:        12
Anonymous UUID:        D39C8D84-3773-71B1-0F0A-850821481972

Time Awake Since Boot: 2400 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'com.firebase.core', reason: '`[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
terminating with uncaught exception of type NSException
abort() called
CoreSimulator 587.35 - Device: iPhone 6s (649A0E13-9AA1-4F2B-9458-99DD1FC2CD19) - Runtime: iOS 12.2 (16E226) - DeviceType: iPhone 6s
Runner Docs:
![ios_Runner](https://user-images.githubusercontent.com/25418424/55148859-10684780-516f-11e9-9af8-62a34d3e34f4.png)
Pods Docs:
![Ios_pod](https://user-images.githubusercontent.com/25418424/55148902-24ac4480-516f-11e9-931f-cc4edf0ea27e.png)

**Comment by sriv** [comment]
I cannot seem to find anything related to gauge or gauge-ruby in this issue. What am I missing?

**Comment by BugDiver** [comment]
Closing it since this issue does not seem to related to gauge-ruby. Feel free to reopen if you think it's an issue with gauge or gauge-ruby.
