### ISSUE TITLE
Add support to filter hooks by tags

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-ruby#12]
Add the ability for users to be able to specify one or more tags when defining hooks. These hooks would be executed when it meets the tag criteria

**Comment by kaustavdm** [comment]
This has been implemented. Waiting for @kashishm to wrap up the documentation before closing this issue.

**Comment by kashishm** [comment]
Implemented via 358d896bffb6b6b3cff5a9242f2939fcd95c34ae
