### ISSUE TITLE
ruby runner with byebug debugger does not work properly

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/gauge-ruby#141]
**Excepted Result**
User should be able to debug ruby project using byebug debugger

**Actual Result**
While entering the byebug's command each character entering into a next line.

**Steps to reproduce:**
prerequisite: 
Install `byebug` debugger `gem install byebug` and include it in the gemfile of gauge-ruby project.
```
  source "https://rubygems.org"
    gem 'test-unit', :group => [:development, :test]
    gem 'byebug'
    gem 'gauge-ruby', '~>0.5.3', :github => 'getgauge/gauge-ruby', :branch => 'master', :group => [:development, :test]
```
- create a gauge-ruby project `gauge init ruby`
- include byebug in step implementation to start debugging and the execution will stop there.
Ex:
```
step 'Vowels in English language are <vowels>.' do |vowels|
  byebug
  @vowels = vowels.scan(/./)
end
```
- perform `gauge run`

**NOTE:** debugger byebug works as expected with gauge version 1.0.5

**Tested environment:**
```
gauge-1.0.7.nightly-2019-10-09
ruby (0.5.3.nightly-2019-10-08)
```

**Comment by BugDiver** [comment]
Gauge supports debugging via VScode. For now, we will not be implementing any other debugger support. Please reopen if it's required.

**Comment by BugDiver** [comment]
Gauge supports debugging via VScode. For now, we will not be implementing any other debugger support. Please reopen it it's required.
