### ISSUE TITLE
Error - Install gauge-ruby plugin

### ISSUE THREAD

**Issue by dalejorm** [getgauge/gauge-ruby#149]
When installing Gauge-Ruby Plugin an error occurs:
execute:
`gauge install ruby`
Response:
`Failed to install plugin 'ruby'.
Reason: Invalid plugin. Could not download ruby-install.json file.
Failed to install plugin 'ruby'.
Reason: Invalid plugin. Could not download ruby-install.json file.`

and I try to install Gauge-Ruby Plugin using the .Zip file and the following error occurs:
execute:
`gauge install --file gauge-ruby-0.5.2-windows.x86.zip`

Response:
`File manifest.json doesn't exist.Panicing : runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc00008b8b8, 0xa545e0, 0x106b9e0)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xae
main.recoverPanic()
        src/github.com/getgauge/gauge/gauge.go:36 +0x5e
panic(0xa545e0, 0x106b9e0)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1c7
github.com/getgauge/gauge/plugin/install.installPluginsFromManifest(0x0, 0xc00010d100)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/plugin/install/install.go:552 +0xa6
github.com/getgauge/gauge/plugin/install.AllPlugins(0x0)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/plugin/install/install.go:480 +0x4e
github.com/getgauge/gauge/cmd.glob..func10(0x1074b60, 0xc00013cfc0, 0x0, 0x2)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/cmd/install.go:36 +0x334
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).execute(0x1074b60, 0xc00013cf80, 0x2, 0x2, 0x1074b60, 0xc00013cf80)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:651 +0x251
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x10764e0, 0xe, 0xc0000f2080, 0xc0000f04b0)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:726 +0x2d3
github.com/getgauge/gauge/vendor/github.com/spf13/cobra.(*Command).Execute(0x10764e0, 0x0, 0xc00008bf78)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/vendor/github.com/spf13/cobra/command.go:685 +0x32
github.com/getgauge/gauge/cmd.Parse(0x0, 0xb51250)
        /Users/stechops/Documents/go-agent-17.4.0/pipelines/Gauge-Build/src/github.com/getgauge/gauge/cmd/cmd.go:154 +0x44
main.main()
        src/github.com/getgauge/gauge/gauge.go:29 +0x45`

Is there another way to install the Gauge-Ruby Plugin on Windows?

**Comment by shubhamsc** [comment]
> Failed to install plugin 'ruby'. Reason: Invalid plugin. Could not download ruby-install.json file.

you'll get this error when you are offline or behind any proxy. If you're behind any proxy, please see the docs to set proxy https://docs.gauge.org/configuration.html?os=windows&language=ruby&ide=vscode#http-proxy-setting-while-using-gauge

>gauge install --file gauge-ruby-0.5.2-windows.x86.zip

Look like you are trying to install a gauge-ruby(x86) zip file which is not compatible with your system. Make sure you are on a 32-bit system or use a gauge-ruby(x86_64) zip file like-
`gauge install ruby --file <path_to>gauge-ruby-0.5.2-windows.x86_64.zip`

**Comment by shubhamsc** [comment]
Closing this issue as you're trying to install gauge-ruby(x86) zip file which is not compatible with your system environment. Feel free to reopen if you still getting the same issue with gauge-ruby(x86_64) zip file.
