### ISSUE TITLE
creating a debug session using pry or bye bug when

### ISSUE THREAD

**Issue by cococoder** [getgauge/gauge-ruby#17]
When I enter a debug session using pry or byebug and I enter text 
gauge forces me to enter each character on a separate line.

Steps to reproduce ( using pry)

* create a scenario
* create a step
* put binding.pry in the step
* run gauge specs

when the code reaches the binding.pry it will enter the Pry REPEL
when you enter text it will put one character per line.

INFO] Executing specification: Specification Heading
[INFO] Executing scenario: First scenario
[INFO] hello gauge
[INFO]
INFO pry(main)>
[INFO] e
[INFO] x
[INFO] i
[INFO] t
[INFO] !
[INFO]

I am using the following versions.

Gauge version: 0.2.1

Plugins
-------
html-report (1.1.0)
ruby (0.1.0)

**Comment by sriv** [comment]
@cococoder - I did some study, and the main reason is that Gauge core is intercepting all stdout and logging them. I have raised [an issue](getgauge/gauge#274) for this.

**Comment by sriv** [comment]
Closing this since the referenced getgauge/gauge#274 is closed.
