### ISSUE TITLE
Unable to complete action gauge init ruby

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#23]
**Expected Behavior**
I should be able to create a ruby project.

**Actual Behavior**
It gives a failure message with incomplete folder structure.

**Steps to replicate**
1. On mac, the following steps
2. gauge --install ruby
3. mkdir rubytest
4. cd rubytest
5. gauge --init ruby
I get the following failure

```
create  /Users/sswaroop/rubytest/step_implementations
 create  /Users/sswaroop/rubytest/step_implementations/step_implementation.rb
 create  /Users/sswaroop/rubytest/env/default/ruby.properties
 error  Failed to copy skel/env/ruby.properties. open /Users/sswaroop/rubytest/env/default/ruby.properties: no such file or directory
 create  /Users/sswaroop/rubytest/Gemfile
 append  /Users/sswaroop/rubytest/Gemfile
Running bundle install.. in /Users/sswaroop/rubytest
Failed to start Gauge Ruby runner. exec: "bundle": executable file not found in $PATH
Failed to initialize project. exit status 1
```

It creates incomplete folder structure.

**Version**

```
Gauge version: 0.4.1.nightly-2016-05-18

Plugins
-------
html-report (2.1.1.nightly-2016-05-19)
java (0.4.1.nightly-2016-05-17)
ruby (0.2.0.nightly-2016-05-17)
```

**Comment by kaustavdm** [comment]
This issue was moved to getgauge/gauge#411

**Comment by sriv** [comment]
The init order change is a result of getgauge/gauge#396. Plugins should be handling presence of directories.

**Comment by apoorvam** [comment]
Fix should be available in nightly > 29-05-2016

**Comment by sguptatw** [comment]
Getting the following error

Could not find gem 'gauge-ruby (~> 0.2.1)' in any of the gem sources listed in
your Gemfile or available on this machine.

**Comment by sriv** [comment]
`gauge init ruby` works fine with:

```
Gauge version: 0.9.1

Plugins
-------
csharp (0.10.1)
html-report (4.0.1)
java (0.6.5)
js (2.0.0)
ruby (0.4.1)
xml-report (0.2.0)

```

@sguptatw - please check.
