### ISSUE TITLE
Linux: unexpected failure message in otherwise successful execution

### ISSUE THREAD

**Issue by srpelissier** [getgauge/gauge-ruby#24]
### Expected behavior
No error since the playback looks successful. 

### Actual behavior
`Failed to start Gauge Ruby runner. exit status 1`

### Steps to reproduce
I run `gauge specs` from bash on xubuntu.
The playback execution is working

Maybe related to:
```
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.1-compliant syntax, but you are running 2.3.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

### Gauge version
```
gauge -v
Gauge version: 0.5.1

Plugins
-------
html-report (2.1.0)
ruby (0.2.1)
```

**Comment by kashishm** [comment]
@srpelissier Thanks for reporting this issue. I could not reproduce this. Could you please share the whole stack trace that might help us replicate the issue.
This error is thrown when `Gauge Ruby` plugin cannot start `gauge-ruby` gem, just make sure you have `gauge-ruby` gem installed on your machine.

**Comment by srpelissier** [comment]
Thanks for your help @kashishm.
I am using gauge and gauge-ruby based on the github.com source code.
I had initialized ruby support via `gauge --install`. But afterwards I installed it from source (again?), and experienced the issue.
A few minutes ago I did ```gauge --uninstall```, tested the gauge API was not working anymore (`Failed to start gauge API: Plugin 'ruby' not installed on following locations : [/home/tester/.gauge/plugins]`), then reinstalled the plugin from source again. `gauge specs` now runs again (see below), but the original message (`exit status 1`) still shows. If I am not mistaken, uninstalling the plugin did not actually remove the file from filesystem, but rather some reference to it which I don't know where to find.
I have no trace because the playback works, but I noticed the modification date of both `$GOPATH/src/github.com/getgauge/gauge-ruby/bin/linux_amd64/gauge-ruby` and `~/.gauge/plugins/ruby/0.2.1/bin/gauge-ruby` were from 3 days ago. I think it was 'locked' by the previously compiled binaries found under `/tmp` in the gauge-ruby source folder. I got rid of these files and compiled/installed it again. Now it has the current date, but the message still shows.
Is there any other info you might need, is the above useful?

```
tester@ubuntuvm1:~/Documents/work/gauge_env/ruby-tut$ gauge specs
warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.1-compliant syntax, but you are running 2.3.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
# Specification Heading
  ## Vowel counts in single word	 ✔ ✔
  ## Vowel counts in multiple word	 ✔ ✔

Successfully generated html-report to => /home/tester/Documents/work/gauge_env/ruby-tut/reports/html-report/2016-06-24 09.20.18
Failed to start Gauge Ruby runner. exit status 1
Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped

Total time taken: 958ms
```
The html report looks OK too (the layout of the html reports is very nice by the way).

**Comment by kashishm** [comment]
Can you share the content of `/home/tester/Documents/work/gauge_env/ruby-tut/manifest.json`?

**Comment by srpelissier** [comment]
```
{
  "Language": "ruby",
  "Plugins": [
    "html-report"
  ]
}
```

**Comment by kashishm** [comment]
Did you change the Gauge or Gauge Ruby src by any chance and then installed it?

Ideally, this should not happen because the execution flow is to start the runner first, then execute and then generate HTML-report.
According to the execution output given by you, it has executed the specs and generated HTML-report and then it is trying to start the runner.
If `Failed to start Gauge Ruby runner. exit status 1` message is shown, then it should not even execute.

Can you please share the output of `gem list gauge-ruby`?

**Comment by srpelissier** [comment]
> Did you change the Gauge or Gauge Ruby src by any chance and then installed it?

No
```
tester@ubuntuvm1:~/Documents/work/gauge_env/ruby-tut$ gem list gauge-ruby

*** LOCAL GEMS ***

gauge-ruby (0.2.1)
```
I agree with you, but I get the message nevertheless. The fact it runs is most important. I don't know what is going on, and I have not touched the source at all.
```
find / -name 'gauge-ruby*' 2>/dev/null
/var/lib/gems/2.3.0/specifications/gauge-ruby-0.2.1.gemspec
/var/lib/gems/2.3.0/cache/gauge-ruby-0.2.1.gem
/var/lib/gems/2.3.0/gems/gauge-ruby-0.2.1
/home/tester/Documents/gopath/src/github.com/getgauge/gauge-ruby
/home/tester/Documents/gopath/src/github.com/getgauge/gauge-ruby/tmp/src/gauge-ruby
/home/tester/Documents/gopath/src/github.com/getgauge/gauge-ruby/tmp/src/gauge-ruby/gauge-ruby.go
/home/tester/Documents/gopath/src/github.com/getgauge/gauge-ruby/tmp/bin/gauge-ruby
/home/tester/Documents/gopath/src/github.com/getgauge/gauge-ruby/bin/linux_amd64/gauge-ruby
/home/tester/Documents/gopath/src/github.com/getgauge/gauge-ruby/gauge-ruby.go
/home/tester/Documents/gopath/src/github.com/getgauge/gauge-ruby/gauge-ruby-0.2.1.gem
/home/tester/Documents/gopath/src/github.com/getgauge/gauge-ruby/gauge-ruby.gemspec
/home/tester/.gauge/plugins/ruby/0.2.1/bin/gauge-ruby
/home/tester/.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/gauge-ruby-0.2.1.gemspec
```

**Comment by mahendrakariya** [comment]
**Dev note:**

The error message `Failed to start Gauge Ruby runner` comes from the gauge-ruby process. The code is at [gauge-ruby.go#L140](https://github.com/getgauge/gauge-ruby/blob/5f3aeddad883dbf6cf8851806cff8d4f54549d9d/gauge-ruby.go#L140).

In the [`runCommand`](https://github.com/getgauge/gauge-ruby/blob/5f3aeddad883dbf6cf8851806cff8d4f54549d9d/gauge-ruby.go#L131) func, Gauge is starting the ruby process using [`cmd.Run()`](https://golang.org/pkg/os/exec/#Cmd.Run). This function will wait for the process to exit. It returns the exit code of the process. In case of non zero code, Gauge prints the reported error.

**Comment by mahendrakariya** [comment]
We should probably print a better error message in such scenarios. In case `cmd.Run()` returns an error, it doesn't always mean there was an issue starting the process.

**Comment by srpelissier** [comment]
I'd be curious to know more about this error. But I don't have time just now, very sorry.

**Comment by kashishm** [comment]
Fix will be available in nightly >= 2016/07/12
