### ISSUE TITLE
MacOS12 bsdthread_register error

### ISSUE THREAD

**Issue by jsia1** [getgauge/gauge-ruby#285]
I am unable to run "bundle exec gauge run specs" using the gauge-ruby template generated with "gauge init ruby"
fatal error: runtime: bsdthread_register error
runtime stack:
runtime.throw(0x12a64ad, 0x21)
	/usr/local/go/src/runtime/panic.go:616 +0x81 fp=0x7ff7bfefed58 sp=0x7ff7bfefed38 pc=0x1028871
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfefed88 sp=0x7ff7bfefed58 pc=0x10263f3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:501 +0xd6 fp=0x7ff7bfefedf0 sp=0x7ff7bfefed88 pc=0x102b166
runtime.rt0_go(0x7ff7bfefee20, 0x2, 0x7ff7bfefee20, 0x1000000, 0x2, 0x7ff7bfeff0f8, 0x7ff7bfeff107, 0x0, 0x7ff7bfeff10f, 0x7ff7bfeff131, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfefedf8 sp=0x7ff7bfefedf0 pc=0x10507b4
Error ----------------------------------

[Gauge]
Failed to start gauge API: Runner with pid 42302 quit unexpectedly(exit status 2)

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
	darwin, 1.4.0, 5cc544c
	html-report (4.1.4), ruby (0.5.2), screenshot (0.0.1), spectacle (0.1.3)
Here is my current Prerequisite packages: (Go, Gauge, Bundler)
$ go version
go version go1.17.6 darwin/amd64
$ gauge -v
Gauge version: 1.4.0
Commit Hash: 5cc544c

Plugins
-------
html-report (4.1.4)
ruby (0.5.2)
screenshot (0.0.1)
spectacle (0.1.3)
$ bundle -v
Bundler version 1.17.3

Please help and question, does this bsdthread_register error relate to an open issue with go on mac os 12?https://github.com/rancher/rancher/issues/35346

**Comment by sriv** [comment]
The error is caused when the go program is built using go 1.10 or older (see https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue)

Can you try installing from source and see if this helps? https://github.com/getgauge/gauge-ruby#build-from-source

**Comment by chadlwilson** [comment]
Closing as seems stale. We can reopen if problem persists on 0.6.0 with gauage 1.5.1 plus :)
