### ISSUE TITLE
Failed to start gauge API: Error : fork/exec bin/gauge-ruby: permission denied

### ISSUE THREAD

**Issue by biswakarma-nc** [getgauge/gauge-ruby#286]
Unable to run my specs with gauge-ruby on Apple M1 Pro running macOS 12.6

I tried “bundle exec gauge run specs” and got below error

biswakarmagochhayat@ICPL25291 system-tests % bundle exec gauge run specs
Error ----------------------------------

[Gauge]
Failed to start gauge API: Error occurred while starting runner process.
Error : fork/exec bin/gauge-ruby: permission denied

Get Support ----------------------------
    Docs:          https://docs.gauge.org/
    Bugs:          https://github.com/getgauge/gauge/issues
    Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	darwin, 1.3.3, 9805a2b
	html-report (4.0.8), ruby (0.5.4), screenshot (0.0.1), xml-report (0.2.2)
	
I confirmed that gauge-ruby gem is installed with version 0.5.4

biswakarmagochhayat@ICPL25291 system-tests % ruby --version   
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]

Any suggestions to resolve this issue are much appreciated.

**Comment by sriv** [comment]
There seems to be some problem in invoking the gauge ruby runner. Please check the permissions of `$HOME/.gauge/plugins/ruby/bin/gauge-ruby` file.
