### ISSUE TITLE
Tag new release for gem upgrades

### ISSUE THREAD

**Issue by gvaibhav1734** [getgauge/gauge-ruby#289]
# Issue
Can we have a new release? (the last release is `0.5.4` in 2020)

# Reason
Dependabot has [updated parser requirement from ~> 2.3 to >= 2.3, < 4.0](https://github.com/getgauge/gauge-ruby/commit/1189120fe91b7d8f93ceeed753bef692f8eb2162) 

Rubocop has been relying on parser >= 3.0.0.0 since [`1.8.0`](https://github.com/rubocop/rubocop/blob/master/relnotes/v1.8.0.md) (latest release `1.52.1`)

Most rails projects using gauge-ruby would also rely on rubocop.
So can we have a new release for this parser version bump?

**Comment by chadlwilson** [comment]
https://github.com/getgauge/gauge-ruby/releases/tag/v0.6.0 has been released which bumps all the dependencies and should relax these constraints.
