### ISSUE TITLE
Generate nightly and install locally

### ISSUE THREAD

**Issue by mahendrakariya** [getgauge/gauge-ruby#32]
- [x] Version the nightlies
- [x] Gauge ruby gem should be made available as part of the plugin distributable (nightly only) and allow local install
- [x] Add build tasks for the above

**Comment by sriv** [comment]
> Gauge ruby gem should be made available as part of the plugin distributable (nightly only) and allow local install

Instead, the vanilla `ruby` template points to HEAD of gauge-ruby in Gemfile of created project, when using nightly version of gauge-ruby.

**Comment by sguptatw** [comment]
Getting an error on running gauge specs
``` 
[ERROR] Cannot import /Users/sswaroop/work/QA/ruby/step_implementations/continue_on_failure.rb. Reason: can't assign Hash to ProtocolBuffers::Field::StringField
```
After doing the following the issue got resolved
```
bundle clean --force
bundle
gem install gauge-ruby
```

**Comment by kashishm** [comment]
Cannot reproduce on latest nightly.

```
Gauge version: 0.6.1

Plugins
-------
ruby (0.3.1.nightly-2016-07-25)
```
