### ISSUE TITLE
uninitialized constant DataStoreFactory?

### ISSUE THREAD

**Issue by tigerlei010** [getgauge/gauge-ruby#36]
gauge-ruby (0.3.1)

In one step define, copy the following lines from the manual:
// Adding value
scenario_store = DataStoreFactory.scenario_datastore;
scenario_store.put("element-id", "455678");

exec gauge specs/ , error occus:
      Specification: specs/example.spec:19
        Error Message: uninitialized constant DataStoreFactory
        Stacktrace:
        /home/tigerlei/work/test/step_implementations/step_implementation.rb:7:in `block in <top (required)>'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/executor.rb:38:in `execute_step'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/processors/execute_step_request_processor.rb:30:in `process_execute_step_request'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/message_processor.rb:52:in `call'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/message_processor.rb:52:in `process_message'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:53:in `handle_message'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:37:in `dispatch_messages'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:76:in `<module:Runtime>'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:29:in `<module:Gauge>'
        /home/tigerlei/.gem/ruby/2.3.0/gems/gauge-ruby-0.3.1/lib/gauge_runtime.rb:27:in `<top (required)>'
        /usr/local/ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        /usr/local/ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        /usr/local/ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'

**Comment by tigerlei010** [comment]
I have solved this problem, add Guage:: before DataStoreFactory. but ,I think modifying the manual http://getgauge.io/documentation/user/current/language_features/data_store.html is still necessary.
![image](https://cloud.githubusercontent.com/assets/3232342/22812963/01393f62-ef83-11e6-9032-50f4eccbe816.png)

**Comment by sguptatw** [comment]
This issue was moved to getgauge/docs.gauge.org#87
