### ISSUE TITLE
Hook messages not sent to gauge

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge-ruby#48]
### Expected Behaviour
Messages in hooks (`Gauge.write_message`) during execution should be sent to Gauge via the `ProtoExecutionResult`.

### Actual Behaviour
Any message written using `Gauge.write_message` in `before_scenario`, `after_scenario`, `before_spec`, `after_spec`, `before_suite` and `after_suite` hooks are not sent back to gauge.

Also, messages in `before_step` and `step`  are sent to gauge after `after_step` hook is executed. 
It should be sent to gauge as soon as that hook is executed.

**Comment by sguptatw** [comment]
Sending messages of step and hooks of steps separately is a tech task. This will be handled as a separate issue.

All the messages are being sent.

**Verified with**
```
Gauge version: 1.0.1.nightly-2018-08-01
Commit Hash: 6aa1ce2

Plugins
-------
ruby (0.5.2.nightly-2018-07-31)
```
