### ISSUE TITLE
Missing gauge ruby X86 library for gauge 0.4.2

### ISSUE THREAD

**Issue by eduarte** [getgauge/gauge-ruby#51]
![image](https://user-images.githubusercontent.com/2123969/35011724-cec2e1f4-facc-11e7-847a-3acd6fdf8426.png)

**Comment by BugDiver** [comment]
@eduarte  We have uploaded the missing windows artifact. Can you please try to install it and verify ?

**Comment by nehashri** [comment]
Closing this issue. If you still find any problems please reopen the issue.
