### ISSUE TITLE
Getting ValidationError for steps with implementation

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#52]
**Expected behavior**
Should get ValidationError only if steps do not have implementation.

**Actual behavior**
Getting ValidationError for steps with implementation

**Steps to replicate**
* `gauge init ruby`
* run specs
`bundle exec gauge run specs`
> Getting validation error for steps with implementation

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-16
Commit Hash: bd76268

Plugins
-------
ruby (0.4.3.nightly-2018-01-17)
```

**Comment by sguptatw** [comment]
This is the same behavior from the command line

**Comment by sguptatw** [comment]
Goto definition does not work as it gives `No definition found for <valid step>`

**Comment by BugDiver** [comment]
[this](https://github.com/getgauge/gauge-ruby/blob/278cdbc83b8ea6df2be216c4fc49de53671c29e1/lib/util.rb#L38) is something which is causing the problem. On windows, the `PROJECT_ROOT` will be set `c:\\User\..` but the [glob](https://github.com/getgauge/gauge-ruby/blob/278cdbc83b8ea6df2be216c4fc49de53671c29e1/lib/static_loader.rb#L26) passes to `Dir`  module requires it to be `C:/Users/something`.
Hence it's not able to scan implementation files.
