### ISSUE TITLE
Duplicate step implementations for steps with no duplicates

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#55]
**Expected behavior**
Should get duplicate step implementation only if steps have multiple implementations.

**Actual behavior**
Switching between spec file and ruby file, we get duplicate step implementation on all steps defined in the file.

**Steps to replicate**
* Create a new gauge-ruby project
* Switch between spec and .rb file
>Note: The duplicate step implementation highlight on all steps.

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-19
Commit Hash: 0c66ca4

Plugins
-------
ruby (0.4.3.nightly-2018-01-18)
```

Bug on story https://github.com/getgauge/gauge-vscode/issues/85

**Comment by sriv** [comment]
Fix should be available in nightly >= 02/06/2018

**Comment by sguptatw** [comment]
This fix seems to have broken Goto definition - https://github.com/getgauge/gauge-vscode/issues/132

> Note: Goto definition works with ruby nightly gauge-ruby-0.4.3.nightly-2018-01-18-windows.x86_64.zip

**Comment by sguptatw** [comment]
Still replicable in 
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
ruby (0.4.3.nightly-2018-02-07)
```
