### ISSUE TITLE
Find usages should be displayed when the file is opened

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#56]
**Actual behavior**
Find usages statistics are not displayed when the implementation file is opened directly.

**Steps to replicate**
* Create a `gauge-ruby` project
* Open a implementation file directly

>Note: Usage statistics are not displayed.

**Version**
```
Gauge version: 0.9.8.nightly-2018-01-30
Commit Hash: 2ed02d8

Plugins
-------
html-report (4.0.3.nightly-2017-12-08)
ruby (0.4.3.nightly-2018-01-18)
```

Bug on story - https://github.com/getgauge/gauge-vscode/issues/85

**Comment by sriv** [comment]
There is a delay between opening an implementation file and the code lens appearing. This is the time taken for gauge-ruby runner to boot up.

However the code lens do appear for me. Is this still an issue?

**Comment by sguptatw** [comment]
I waited for more than 1 minute. The code lens do not appear. However if I open a spec file first, then the code lens appears.

Try the following scenario
* Open VSCode.
* Open a implementation file (Close all other files including Welcome Page)
* Re-open the project

> The implementation file does not show the find usage statistics

**Version**
```
VSCode - gauge-0.0.4.nightly-2018-02-02.vsix
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
ruby (0.4.3.nightly-2018-01-18)
```

**Comment by sriv** [comment]
> - Open VSCode.
> - Open a implementation file (Close all other files including Welcome Page)
> - Re-open the project

Works for me, perhaps you can try with the nightly once it is out for 02/06/2018

**Comment by sguptatw** [comment]
Working as expected in
```
Gauge version: 1.0.1.nightly-2018-07-31
Commit Hash: 4ae7c9a

Plugins
-------
ruby (0.5.2.nightly-2018-07-31)
```
