### ISSUE TITLE
Screenshots are not visible in the HTML reports

### ISSUE THREAD

**Issue by navaneeth** [getgauge/gauge-ruby#6]
There are no screenshots in the HTML reports when there are failures

**Comment by sriv** [comment]
You must be on Linux or Windows. The current implementation takes screenshot only on Mac, only because that was easy.

We need to figure out a way to capture screenshot on other OSes. The best bet on Linux seems to be using Imagemagick. Any other suggestions?

Better luck on windows - we could use https://github.com/jarmo/win32screenshot.

**Comment by navaneeth** [comment]
I'm on Mac (Yosemite). 

A better design would be to write a screenshot utility which works cross-platform on `go`. Then distribute that together with `gauge`. And all runners can just invoke this executable to take a screenshot. With this, you don't have to find compatible libraries for taking screenshots with each programming languages/runners. 

I'd do this as a separate go project & repository and let gauge depend on this. Take a look at https://github.com/vova616/screenshot. They already have implementation for Windows & Linux. We can add OSX support by invoking the `screencapture` command. 

With this, all runners will take screenshot consistently and new ones can just use this utility. 

Thoughts?

**Comment by sriv** [comment]
Good idea. On the same lines, how would it look if Gauge took over the responsibility of taking screenshots? Whenever the `ExecutionStatusResponse` contains `failed: true`, then Gauge takes the screenshot, instead of the runner taking screenshot and passing the bytes?

**Comment by vishnukarthikl** [comment]
Just thinking ahead, But if we get the remote execution working, then it
wouldn't make sense for gauge to have the responsibility of taking
screenshot.

**Comment by sriv** [comment]
Fair enough, separate utility it is then.

**Comment by prateekbaheti** [comment]
Yeah the separate utility makes sense. And this would work in the case of remote execution too. 
There is also an [issue](https://github.com/getgauge/gauge/issues/9) on providing a hook for custom screenshots so users can write their own screenshot mechanism.

**Comment by navaneeth** [comment]
I'd vote for separate utility and runners invoking it.

**Comment by sriv** [comment]
Fixed via 7fa4b8b60afae30e456210c0748d25cdcf16911c
