### ISSUE TITLE
[Optimization] Reduce the time taken by FTs

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#72]
**Proposed behavior**
The time taken to execute Ruby-FTs should be comparable to Java-FTs

**Actual behavior**
The time taken is considerable when compared to Java-FTs

**Comment by sriv** [comment]
tests now use a cache of bundler. should be faster

**Comment by zabil** [comment]
@sriv for reference can you explain how you configured that?

**Comment by sriv** [comment]
sure. 

The changes are in two places:

1) ruby templates 

The template has a `create_gemfile.rb` that generates the `Gemfile` and invokes `bundle install`. It used to hardcode the path to `vendor/bundle`. Now it shall look for an env `GAUGE_BUNDLER_CACHE_PATH` and use that as bundler cache directory.

2) gauge-tests

Set `GAUGE_BUNDLER_CACHE_PATH` = `resources/LocalBundler` when invoking gauge. This is propogated to subprocesses.

Thus, the first run gets everything from rubygems/github and subsequent runs will use the cache.

**Comment by sguptatw** [comment]
Works on Darwin, however not on Linux - https://github.com/getgauge/gauge-ruby/issues/74

**Comment by sriv** [comment]
Update,

Rather than doing this roundabout hackery, I just removed the `--path` from `create_gemfile.rb`.

We will now piggyback on bundler's caching. for custom cache path, users can set `BUNDLE_PATH` env. ref: http://bundler.io/v1.2/bundle_install.html
