### ISSUE TITLE
[Linux] Getting Error `bundle install` before trying to start your application

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#74]
_From @sguptatw on April 24, 2018 12:55_

**Expected behavior**
Should be able to run tests seamlessly

**Actual behavior**
Getting `Please run bundle install before trying to start your application` and fails the test

**Observed on**
https://build.getgauge.io/go/tab/build/detail/Ruby-FT/1100/specs/1/linux

_Copied from original issue: getgauge/gauge-tests#21_

**Comment by sriv** [comment]
https://travis-ci.org/getgauge/gauge-ruby/jobs/367055158
