### ISSUE TITLE
Configured debug type `Ruby` is not supported

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#78]
**Expected behavior**
Should be able to debug

**Actual behavior**
Getting the error `Configured debug type `Ruby` is not supported`

**Steps to replicate**
* Create a new `gauge-ruby` project
* Click on `Debug Spec`
> The above message is displayed

**Version**
```
Gauge version: 0.9.8.nightly-2018-05-01
Commit Hash: 765d3e7

Plugins
-------
ruby (0.5.0.nightly-2018-04-16)
```

**Comment by BugDiver** [comment]
@sguptatw Gauge tries to attach the existing debugger to the runner. You need to install the `vscode-ruby` extension to get the debugger.

**Comment by sguptatw** [comment]
Expected - [VSCode Ruby](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) has to be installed.

**Comment by Ben-Garcia-DB-Solutions** [comment]
VSCode Ruby is now depreciated.

**Comment by mirzalazuardi** [comment]
any update to fix this ?
