### ISSUE TITLE
Getting encryption Warning during initialization

### ISSUE THREAD

**Issue by sswaroopgupta** [getgauge/gauge-ruby#87]
**Expected behavior**
Should not get this warning

**Actual behavior**
```
The git source `git://github.com/getgauge/gauge-ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```
**Steps to replicate**
* `gauge init ruby`
> The warning is displayed

**Comment by sriv** [comment]
this will happen only on nightly or source builds of `gauge-ruby`

Problem lies in the Gemfile generated in the template: https://github.com/getgauge/gauge-repository/blob/master/templates/ruby/create_gemfile.rb#L23

Solution is to use `https` endpoint and not the `github` source. Ref: https://bundler.io/v1.16/guides/git.html#security
