### ISSUE TITLE
Should be able to run specs after initializing project

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#90]
**Actual behavior**
Getting the message
```
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/
```
**Steps to replicate**
* Create gauge-ruby project
* Run `bundle install`
> The above message is displayed
After MSYS2 is installed gauge run specs is working as expected on Windows.

**Comment by BugDiver** [comment]
The `MSY2`is needed to build the native C-based extension (on windows). I guess `ruby` installers install MYSSY2 along with ruby but `choco` does not.
Installing `MYSYS2` explicitly should resolve this issue.
