### ISSUE TITLE
The usage statistics should not repeat after changing the implementation file content

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-ruby#91]
**Actual behavior**
The usage statistics are repeated

**Steps to replicate**
* Create a `gauge-ruby` project
* Add a new line as the first line inside a step implementation method
> The usage statistics reflect multiple times

![usage_statistics](https://user-images.githubusercontent.com/6310197/42165037-0c3dff92-7e25-11e8-9273-5a21c1883ebe.png)

**Version**
```
Gauge version: 1.0.1.nightly-2018-06-27
Commit Hash: 0e3c1fc

Plugins
-------
ruby (0.5.2.nightly-2018-06-19)
```

**Comment by shubhamsc** [comment]
Fixed should be available in nightly >= 30-07-18
